version: 1
validation: sovereign
default_denom: usc
build:
  main: ./cmd/spiderd
accounts: 
- name: alice
  coins:
    - 100000000000usc
- name: bob
  coins:
    - 50000000000usc
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
    - 5usc
validators:
  - name: alice
    bonded: 10000000000usc
genesis:
  app_state:
    staking:
      params:
        bond_denom: usc
    crisis:
      constant_fee:
        denom: usc
        amount: "1000"
    gov:
      params:
        min_deposit:
          - denom: usc
            amount: "10000000"
    mint:
      params:
        mint_denom: usc
    official:
      operator_map:
        - {address: spider1gnx609p4e8p3snwm54f204pnncmy99ltm2w3wr}
    tokenfactory:
      params:
        creation_fee:
          denom: usc
          amount: "100"
