// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: spider/loan/v1/loan.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Loan defines the Loan message.
type Loan struct {
	Borrower                string `protobuf:"bytes,1,opt,name=borrower,proto3" json:"borrower,omitempty"`
	Status                  uint64 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Seq                     uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Term                    uint64 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	ApproveDeadline         uint64 `protobuf:"varint,5,opt,name=approve_deadline,json=approveDeadline,proto3" json:"approve_deadline,omitempty"`
	RepayDeadline           uint64 `protobuf:"varint,6,opt,name=repay_deadline,json=repayDeadline,proto3" json:"repay_deadline,omitempty"`
	PublicLiquidationDelay  uint64 `protobuf:"varint,7,opt,name=public_liquidation_delay,json=publicLiquidationDelay,proto3" json:"public_liquidation_delay,omitempty"`
	PublicLiquidationReward string `protobuf:"bytes,8,opt,name=public_liquidation_reward,json=publicLiquidationReward,proto3" json:"public_liquidation_reward,omitempty"`
	Amount                  string `protobuf:"bytes,9,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                     string `protobuf:"bytes,10,opt,name=fee,proto3" json:"fee,omitempty"`
	Lender                  string `protobuf:"bytes,11,opt,name=lender,proto3" json:"lender,omitempty"`
	CollateralType          string `protobuf:"bytes,12,opt,name=collateral_type,json=collateralType,proto3" json:"collateral_type,omitempty"`
	CollateralCoin          string `protobuf:"bytes,13,opt,name=collateral_coin,json=collateralCoin,proto3" json:"collateral_coin,omitempty"`
	CollateralNftClass      string `protobuf:"bytes,14,opt,name=collateral_nft_class,json=collateralNftClass,proto3" json:"collateral_nft_class,omitempty"`
	CollateralNftId         string `protobuf:"bytes,15,opt,name=collateral_nft_id,json=collateralNftId,proto3" json:"collateral_nft_id,omitempty"`
}

func (m *Loan) Reset()         { *m = Loan{} }
func (m *Loan) String() string { return proto.CompactTextString(m) }
func (*Loan) ProtoMessage()    {}
func (*Loan) Descriptor() ([]byte, []int) {
	return fileDescriptor_986227c984fae19c, []int{0}
}
func (m *Loan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Loan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Loan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Loan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loan.Merge(m, src)
}
func (m *Loan) XXX_Size() int {
	return m.Size()
}
func (m *Loan) XXX_DiscardUnknown() {
	xxx_messageInfo_Loan.DiscardUnknown(m)
}

var xxx_messageInfo_Loan proto.InternalMessageInfo

func (m *Loan) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *Loan) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Loan) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Loan) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Loan) GetApproveDeadline() uint64 {
	if m != nil {
		return m.ApproveDeadline
	}
	return 0
}

func (m *Loan) GetRepayDeadline() uint64 {
	if m != nil {
		return m.RepayDeadline
	}
	return 0
}

func (m *Loan) GetPublicLiquidationDelay() uint64 {
	if m != nil {
		return m.PublicLiquidationDelay
	}
	return 0
}

func (m *Loan) GetPublicLiquidationReward() string {
	if m != nil {
		return m.PublicLiquidationReward
	}
	return ""
}

func (m *Loan) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Loan) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *Loan) GetLender() string {
	if m != nil {
		return m.Lender
	}
	return ""
}

func (m *Loan) GetCollateralType() string {
	if m != nil {
		return m.CollateralType
	}
	return ""
}

func (m *Loan) GetCollateralCoin() string {
	if m != nil {
		return m.CollateralCoin
	}
	return ""
}

func (m *Loan) GetCollateralNftClass() string {
	if m != nil {
		return m.CollateralNftClass
	}
	return ""
}

func (m *Loan) GetCollateralNftId() string {
	if m != nil {
		return m.CollateralNftId
	}
	return ""
}

func init() {
	proto.RegisterType((*Loan)(nil), "spider.loan.v1.Loan")
}

func init() { proto.RegisterFile("spider/loan/v1/loan.proto", fileDescriptor_986227c984fae19c) }

var fileDescriptor_986227c984fae19c = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0x16, 0xca, 0x66, 0x58, 0x32, 0x0c, 0x1a, 0xee, 0x0e, 0xd1, 0x84, 0x84, 0x18,
	0x48, 0xac, 0x4c, 0x5c, 0x10, 0x47, 0xb6, 0x0b, 0xd2, 0xc4, 0xa1, 0xe2, 0xc4, 0x25, 0x72, 0xe3,
	0x57, 0xc9, 0x92, 0x6b, 0xbb, 0xb6, 0xd3, 0x92, 0x6f, 0xc1, 0x99, 0x4f, 0xc4, 0xb1, 0x47, 0x8e,
	0xa8, 0xfd, 0x22, 0xc8, 0x2f, 0x51, 0x03, 0x65, 0xa7, 0xbc, 0xff, 0xff, 0xf7, 0x7b, 0x87, 0x58,
	0x8f, 0x8c, 0xbc, 0x95, 0x02, 0xdc, 0x58, 0x19, 0xae, 0xc7, 0xcb, 0x2b, 0xfc, 0x5e, 0x5a, 0x67,
	0x82, 0xa1, 0x59, 0x8b, 0x2e, 0xb1, 0x5a, 0x5e, 0x9d, 0x8d, 0x2a, 0xe3, 0xe7, 0xc6, 0x97, 0x48,
	0xc7, 0x6d, 0x68, 0xd5, 0xe7, 0x3f, 0x52, 0x92, 0xde, 0x1a, 0xae, 0xe9, 0x19, 0x39, 0x9c, 0x1a,
	0xe7, 0xcc, 0x0a, 0x1c, 0x4b, 0xce, 0x93, 0x8b, 0xa3, 0xc9, 0x2e, 0xd3, 0x53, 0x32, 0xf4, 0x81,
	0x87, 0xda, 0xb3, 0x7b, 0xe7, 0xc9, 0x45, 0x3a, 0xe9, 0x12, 0x3d, 0x21, 0x07, 0x1e, 0x16, 0xec,
	0x00, 0xcb, 0x38, 0x52, 0x4a, 0xd2, 0x00, 0x6e, 0xce, 0x52, 0xac, 0x70, 0xa6, 0xaf, 0xc8, 0x09,
	0xb7, 0xd6, 0x99, 0x25, 0x94, 0x02, 0xb8, 0x50, 0x52, 0x03, 0xbb, 0x8f, 0x3c, 0xef, 0xfa, 0x9b,
	0xae, 0xa6, 0x2f, 0x48, 0xe6, 0xc0, 0xf2, 0xa6, 0x17, 0x87, 0x28, 0x1e, 0x63, 0xbb, 0xd3, 0xde,
	0x13, 0x66, 0xeb, 0xa9, 0x92, 0x55, 0xa9, 0xe4, 0xa2, 0x96, 0x82, 0x07, 0x69, 0x74, 0x29, 0x40,
	0xf1, 0x86, 0x3d, 0xc0, 0x85, 0xd3, 0x96, 0xdf, 0xf6, 0xf8, 0x26, 0x52, 0xfa, 0x81, 0x8c, 0xee,
	0xd8, 0x74, 0xb0, 0xe2, 0x4e, 0xb0, 0x43, 0xfc, 0xed, 0x67, 0xff, 0xad, 0x4e, 0x10, 0xc7, 0x57,
	0xe0, 0x73, 0x53, 0xeb, 0xc0, 0x8e, 0x50, 0xec, 0x52, 0x7c, 0x85, 0x19, 0x00, 0x23, 0x58, 0xc6,
	0x31, 0x9a, 0x0a, 0xb4, 0x00, 0xc7, 0x1e, 0xb6, 0x66, 0x9b, 0xe8, 0x4b, 0x92, 0x57, 0x46, 0x29,
	0x1e, 0xc0, 0x71, 0x55, 0x86, 0xc6, 0x02, 0x7b, 0x84, 0x42, 0xd6, 0xd7, 0x5f, 0x1a, 0x0b, 0x7b,
	0x62, 0x65, 0xa4, 0x66, 0xc7, 0xfb, 0xe2, 0xb5, 0x91, 0x9a, 0xbe, 0x25, 0x4f, 0xff, 0x12, 0xf5,
	0x2c, 0x94, 0x95, 0xe2, 0xde, 0xb3, 0x0c, 0x6d, 0xda, 0xb3, 0xcf, 0xb3, 0x70, 0x1d, 0x09, 0x7d,
	0x4d, 0x1e, 0xef, 0x6d, 0x48, 0xc1, 0x72, 0xd4, 0xf3, 0x7f, 0xf4, 0x4f, 0xe2, 0xe3, 0x9b, 0x9f,
	0x9b, 0x22, 0x59, 0x6f, 0x8a, 0xe4, 0xf7, 0xa6, 0x48, 0xbe, 0x6f, 0x8b, 0xc1, 0x7a, 0x5b, 0x0c,
	0x7e, 0x6d, 0x8b, 0xc1, 0xd7, 0x27, 0xdd, 0xf1, 0x7d, 0x6b, 0xcf, 0x2f, 0xfe, 0x8a, 0x9f, 0x0e,
	0xf1, 0xa4, 0xde, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xee, 0x69, 0x7c, 0x9c, 0x9a, 0x02, 0x00,
	0x00,
}

func (m *Loan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Loan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Loan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CollateralNftId) > 0 {
		i -= len(m.CollateralNftId)
		copy(dAtA[i:], m.CollateralNftId)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.CollateralNftId)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.CollateralNftClass) > 0 {
		i -= len(m.CollateralNftClass)
		copy(dAtA[i:], m.CollateralNftClass)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.CollateralNftClass)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.CollateralCoin) > 0 {
		i -= len(m.CollateralCoin)
		copy(dAtA[i:], m.CollateralCoin)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.CollateralCoin)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.CollateralType) > 0 {
		i -= len(m.CollateralType)
		copy(dAtA[i:], m.CollateralType)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.CollateralType)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Lender) > 0 {
		i -= len(m.Lender)
		copy(dAtA[i:], m.Lender)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.Lender)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.PublicLiquidationReward) > 0 {
		i -= len(m.PublicLiquidationReward)
		copy(dAtA[i:], m.PublicLiquidationReward)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.PublicLiquidationReward)))
		i--
		dAtA[i] = 0x42
	}
	if m.PublicLiquidationDelay != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.PublicLiquidationDelay))
		i--
		dAtA[i] = 0x38
	}
	if m.RepayDeadline != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.RepayDeadline))
		i--
		dAtA[i] = 0x30
	}
	if m.ApproveDeadline != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.ApproveDeadline))
		i--
		dAtA[i] = 0x28
	}
	if m.Term != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.Term))
		i--
		dAtA[i] = 0x20
	}
	if m.Seq != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.Seq))
		i--
		dAtA[i] = 0x18
	}
	if m.Status != 0 {
		i = encodeVarintLoan(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintLoan(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLoan(dAtA []byte, offset int, v uint64) int {
	offset -= sovLoan(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Loan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovLoan(uint64(m.Status))
	}
	if m.Seq != 0 {
		n += 1 + sovLoan(uint64(m.Seq))
	}
	if m.Term != 0 {
		n += 1 + sovLoan(uint64(m.Term))
	}
	if m.ApproveDeadline != 0 {
		n += 1 + sovLoan(uint64(m.ApproveDeadline))
	}
	if m.RepayDeadline != 0 {
		n += 1 + sovLoan(uint64(m.RepayDeadline))
	}
	if m.PublicLiquidationDelay != 0 {
		n += 1 + sovLoan(uint64(m.PublicLiquidationDelay))
	}
	l = len(m.PublicLiquidationReward)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.Lender)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.CollateralType)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.CollateralCoin)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.CollateralNftClass)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	l = len(m.CollateralNftId)
	if l > 0 {
		n += 1 + l + sovLoan(uint64(l))
	}
	return n
}

func sovLoan(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLoan(x uint64) (n int) {
	return sovLoan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Loan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLoan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Loan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Loan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Term", wireType)
			}
			m.Term = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Term |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApproveDeadline", wireType)
			}
			m.ApproveDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApproveDeadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepayDeadline", wireType)
			}
			m.RepayDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RepayDeadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicLiquidationDelay", wireType)
			}
			m.PublicLiquidationDelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PublicLiquidationDelay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicLiquidationReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicLiquidationReward = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralCoin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralCoin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralNftClass", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralNftClass = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralNftId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralNftId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLoan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLoan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLoan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLoan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLoan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLoan
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLoan
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLoan
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLoan        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLoan          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLoan = fmt.Errorf("proto: unexpected end of group")
)
