// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: spider/snft/v1/class_owner.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClassOwner defines the ClassOwner message.
type ClassOwner struct {
	ClassId      string     `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	PendingOwner string     `protobuf:"bytes,2,opt,name=pending_owner,json=pendingOwner,proto3" json:"pending_owner,omitempty"`
	CreationFee  types.Coin `protobuf:"bytes,3,opt,name=creation_fee,json=creationFee,proto3" json:"creation_fee"`
	Owner        string     `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *ClassOwner) Reset()         { *m = ClassOwner{} }
func (m *ClassOwner) String() string { return proto.CompactTextString(m) }
func (*ClassOwner) ProtoMessage()    {}
func (*ClassOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_d914ab970cacf9f8, []int{0}
}
func (m *ClassOwner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClassOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClassOwner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClassOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassOwner.Merge(m, src)
}
func (m *ClassOwner) XXX_Size() int {
	return m.Size()
}
func (m *ClassOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassOwner.DiscardUnknown(m)
}

var xxx_messageInfo_ClassOwner proto.InternalMessageInfo

func (m *ClassOwner) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *ClassOwner) GetPendingOwner() string {
	if m != nil {
		return m.PendingOwner
	}
	return ""
}

func (m *ClassOwner) GetCreationFee() types.Coin {
	if m != nil {
		return m.CreationFee
	}
	return types.Coin{}
}

func (m *ClassOwner) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func init() {
	proto.RegisterType((*ClassOwner)(nil), "spider.snft.v1.ClassOwner")
}

func init() { proto.RegisterFile("spider/snft/v1/class_owner.proto", fileDescriptor_d914ab970cacf9f8) }

var fileDescriptor_d914ab970cacf9f8 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x63, 0x28, 0xff, 0xdc, 0xc2, 0x10, 0x3a, 0xb4, 0x1d, 0x4c, 0x04, 0x4b, 0x17, 0x6c,
	0x05, 0xde, 0x20, 0x95, 0x90, 0x98, 0x90, 0x3a, 0xb2, 0x54, 0xf9, 0x73, 0x8d, 0x2c, 0x81, 0x2f,
	0x8a, 0xa3, 0x00, 0x6f, 0xc1, 0x53, 0xf0, 0x2c, 0x1d, 0x3b, 0x32, 0x21, 0x94, 0xbc, 0x08, 0xb2,
	0x2f, 0x6c, 0x77, 0xe7, 0xef, 0xee, 0xfb, 0xf9, 0xe3, 0x91, 0xad, 0x74, 0x01, 0xb5, 0xb2, 0x66,
	0xdb, 0xa8, 0x36, 0x56, 0xf9, 0x4b, 0x6a, 0xed, 0x06, 0xdf, 0x0c, 0xd4, 0xb2, 0xaa, 0xb1, 0xc1,
	0xf0, 0x82, 0x14, 0xd2, 0x29, 0x64, 0x1b, 0x2f, 0x44, 0x8e, 0xf6, 0x15, 0xad, 0xca, 0x52, 0x0b,
	0xaa, 0x8d, 0x33, 0x68, 0xd2, 0x58, 0xe5, 0xa8, 0x0d, 0xe9, 0x17, 0xd3, 0x12, 0x4b, 0xf4, 0xa5,
	0x72, 0x15, 0x4d, 0xaf, 0xbf, 0x18, 0xe7, 0x2b, 0x77, 0xfb, 0xc9, 0x9d, 0x0e, 0xe7, 0xfc, 0x94,
	0x9c, 0x74, 0x31, 0x63, 0x11, 0x5b, 0x9e, 0xad, 0x4f, 0x7c, 0xff, 0x58, 0x84, 0x37, 0xfc, 0xbc,
	0x02, 0x53, 0x68, 0x53, 0x12, 0xc6, 0xec, 0xc0, 0xbf, 0x4f, 0x86, 0x21, 0xed, 0x27, 0x7c, 0x92,
	0xd7, 0x90, 0x36, 0x1a, 0xcd, 0x66, 0x0b, 0x30, 0x3b, 0x8c, 0xd8, 0x72, 0x7c, 0x37, 0x97, 0xc4,
	0x26, 0x1d, 0x9b, 0x1c, 0xd8, 0xe4, 0x0a, 0xb5, 0x49, 0x46, 0xbb, 0x9f, 0xab, 0x60, 0x3d, 0xfe,
	0x5f, 0x7a, 0x00, 0x08, 0xa7, 0xfc, 0x88, 0x0c, 0x46, 0xde, 0x80, 0x9a, 0xe4, 0x76, 0xd7, 0x09,
	0xb6, 0xef, 0x04, 0xfb, 0xed, 0x04, 0xfb, 0xec, 0x45, 0xb0, 0xef, 0x45, 0xf0, 0xdd, 0x8b, 0xe0,
	0xf9, 0x72, 0x88, 0xea, 0x9d, 0xc2, 0x6a, 0x3e, 0x2a, 0xb0, 0xd9, 0xb1, 0xff, 0xde, 0xfd, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x61, 0x44, 0x58, 0x48, 0x01, 0x00, 0x00,
}

func (m *ClassOwner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassOwner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClassOwner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintClassOwner(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.CreationFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClassOwner(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.PendingOwner) > 0 {
		i -= len(m.PendingOwner)
		copy(dAtA[i:], m.PendingOwner)
		i = encodeVarintClassOwner(dAtA, i, uint64(len(m.PendingOwner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintClassOwner(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintClassOwner(dAtA []byte, offset int, v uint64) int {
	offset -= sovClassOwner(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClassOwner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovClassOwner(uint64(l))
	}
	l = len(m.PendingOwner)
	if l > 0 {
		n += 1 + l + sovClassOwner(uint64(l))
	}
	l = m.CreationFee.Size()
	n += 1 + l + sovClassOwner(uint64(l))
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovClassOwner(uint64(l))
	}
	return n
}

func sovClassOwner(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClassOwner(x uint64) (n int) {
	return sovClassOwner(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClassOwner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassOwner
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassOwner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassOwner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassOwner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassOwner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassOwner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassOwner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassOwner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassOwner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassOwner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassOwner
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassOwner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassOwner
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassOwner
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassOwner
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassOwner(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassOwner
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClassOwner(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClassOwner
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClassOwner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClassOwner
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClassOwner
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClassOwner
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClassOwner
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClassOwner        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClassOwner          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClassOwner = fmt.Errorf("proto: unexpected end of group")
)
